#include "lock/lockfile.hpp"
#include "lock/resolver.hpp"
#include "repo/bin_repo.hpp"
#include "store/store.hpp"
#include "util/file.hpp"
#include "util/parse.hpp"
#include "config/conf.hpp"
#include <algorithm>
#include <cctype>
#include <sstream>
#include <iomanip>
#include <chrono>
#include <iostream>

namespace lock {

namespace {

std::string current_timestamp() {
    auto now = std::chrono::system_clock::now();
    auto in_time_t = std::chrono::system_clock::to_time_t(now);
    
    std::ostringstream ss;
    ss << std::put_time(std::localtime(&in_time_t), "%Y-%m-%dT%H:%M:%S%z");
    return ss.str();
}

} // anonymous namespace

Lockfile read(const std::filesystem::path& lock_path) {
    Lockfile lock;
    
    if (!std::filesystem::exists(lock_path)) {
        return lock;
    }
    
    std::string content = util::read_file(lock_path);
    std::istringstream iss(content);
    
    LockEntry* current_entry = nullptr;
    std::string line;
    
    while (std::getline(iss, line)) {
        line = util::trim(line);
        
        if (line.empty() || line[0] == '#') {
            continue;
        }
        
        // Check for section headers
        if (line[0] == '[' && line.back() == ']') {
            std::string name = line.substr(1, line.size() - 2);
            lock.entries.push_back(LockEntry{});
            current_entry = &lock.entries.back();
            current_entry->name = name;
            continue;
        }
        
        if (!current_entry) continue;
        
        auto eq_pos = line.find('=');
        if (eq_pos == std::string::npos) continue;
        
        std::string key = util::trim(line.substr(0, eq_pos));
        std::string value = util::extract_value(line);
        
        if (key == "version") {
            current_entry->version = value;
        } else if (key == "url") {
            current_entry->url = value;
        } else if (key == "checksum") {
            current_entry->checksum = value;
        } else if (key == "store") {
            current_entry->store_path = value;
        } else if (key == "built") {
            if (value == "system") {
                current_entry->build_kind = BuildKind::System;
            } else if (value == "source") {
                current_entry->build_kind = BuildKind::Source;
            } else {
                current_entry->build_kind = BuildKind::Prebuilt;
            }
        } else if (key == "locked") {
            lock.generated_at = value;
        }
    }
    
    return lock;
}

void write(const Lockfile& lock, const std::filesystem::path& lock_path) {
    std::ostringstream oss;
    
    oss << "# Generated by astral-env lock — do not edit manually\n";
    oss << "# astral-env " << lock.astral_env_version << "\n";
    oss << "# locked: " << lock.generated_at << "\n\n";
    
    for (const auto& entry : lock.entries) {
        oss << "[" << entry.name << "]\n";
        oss << "version  = \"" << entry.version << "\"\n";
        oss << "url      = \"" << entry.url << "\"\n";
        oss << "checksum = \"" << entry.checksum << "\"\n";
        oss << "store    = \"" << entry.store_path.string() << "\"\n";
        oss << "built    = \"";
        switch (entry.build_kind) {
            case BuildKind::System:   oss << "system"; break;
            case BuildKind::Source:   oss << "source"; break;
            case BuildKind::Prebuilt: oss << "prebuilt"; break;
        }
        oss << "\"\n\n";
    }
    
    util::write_file(lock_path, oss.str());
}

Lockfile generate(
    const std::filesystem::path& stars_path,
    const std::filesystem::path& repo_bin_dir,
    bool,
    const std::vector<std::string>&
) {
    Lockfile lock;
    lock.astral_env_version = config::version();
    lock.generated_at = current_timestamp();
    
    if (!std::filesystem::exists(stars_path)) {
        throw std::runtime_error("File not found: " + stars_path.string());
    }
    
    std::string content = util::read_file(stars_path);
    std::istringstream iss(content);
    
    bool in_packages = false;
    std::string line;
    
    while (std::getline(iss, line)) {
        line = util::trim(line);
        
        if (line.empty() || line[0] == '#') {
            continue;
        }
        
        if (line.find("$ENV.Packages") != std::string::npos) {
            in_packages = true;
            continue;
        }
        
        if (line == "};") {
            in_packages = false;
            continue;
        }
        
        if (!in_packages) continue;
        
        // Skip metadata block markers
        if (line.find("$ENV.") != std::string::npos) {
            continue;
        }
        
        // Skip Metadata block entirely
        if (line.find("Metadata") != std::string::npos ||
            line.find("Vars") != std::string::npos ||
            line.find("Shell") != std::string::npos) {
            in_packages = false;
            continue;
        }
        
        // Parse package constraint
        auto constraint = lock::parse_constraint(line);
        
        // Resolve the package constraint
        auto resolved = lock::resolve(repo_bin_dir, constraint);
        
        if (!resolved) {
            // If not found in bin/ and it's NOT an explicit -bin request,
            // create a synthetic entry for system install via astral -S
            bool explicit_bin = constraint.package.ends_with("-bin");
            if (!explicit_bin) {
                // Create a system install entry
                LockEntry entry;
                entry.name = constraint.package;
                entry.version = "";
                entry.url = "";
                entry.checksum = "";
                entry.store_path = "";
                entry.build_kind = BuildKind::System;
                entry.build_script = std::nullopt;
                lock.entries.push_back(entry);
            } else {
                std::cerr << "Error: Package '" << constraint.package << "' not found in bin/ repo.\n";
                throw std::runtime_error("Package not found: " + constraint.package);
            }
            continue;
        }
        
        LockEntry entry;
        entry.name = resolved->name;
        entry.version = resolved->version;
        entry.url = resolved->url;
        entry.checksum = resolved->checksum;
        entry.build_script = resolved->build_script;
        
        // Determine build kind based on what's in the resolved entry
        if (resolved->via_astral) {
            entry.build_kind = BuildKind::System;
            entry.store_path = "";
        } else if (resolved->build_script && !resolved->build_script->empty()) {
            entry.build_kind = BuildKind::Source;
            // Compute store path
            entry.store_path = store::store_path(
                "/astral-env/store",
                entry.name,
                entry.version,
                entry.checksum
            );
        } else {
            entry.build_kind = BuildKind::Prebuilt;
            // Compute store path
            entry.store_path = store::store_path(
                "/astral-env/store",
                entry.name,
                entry.version,
                entry.checksum
            );
        }
        
        lock.entries.push_back(entry);
    }
    
    return lock;
}

} // namespace lock
