#include "lock/lockfile.hpp"
#include "lock/resolver.hpp"
#include "repo/bin_repo.hpp"
#include "store/store.hpp"
#include "util/file.hpp"
#include "util/parse.hpp"
#include "config/conf.hpp"
#include <algorithm>
#include <cctype>
#include <sstream>
#include <iomanip>
#include <chrono>
#include <iostream>

namespace lock {

namespace {

std::string current_timestamp() {
    auto now = std::chrono::system_clock::now();
    auto in_time_t = std::chrono::system_clock::to_time_t(now);
    std::ostringstream ss;
    ss << std::put_time(std::localtime(&in_time_t), "%Y-%m-%dT%H:%M:%S%z");
    return ss.str();
}

} // anonymous namespace

Lockfile read(const std::filesystem::path& lock_path) {
    Lockfile lock;
    if (!std::filesystem::exists(lock_path)) return lock;

    std::string content = util::read_file(lock_path);
    std::istringstream iss(content);

    LockEntry* current_entry = nullptr;
    std::string line;

    while (std::getline(iss, line)) {
        line = util::trim(line);
        if (line.empty() || line[0] == '#') continue;

        if (line[0] == '[' && line.back() == ']') {
            lock.entries.push_back(LockEntry{});
            current_entry = &lock.entries.back();
            current_entry->name = line.substr(1, line.size() - 2);
            continue;
        }

        if (!current_entry) continue;

        auto eq_pos = line.find('=');
        if (eq_pos == std::string::npos) continue;

        std::string key   = util::trim(line.substr(0, eq_pos));
        std::string value = util::extract_value(line);

        if      (key == "version")  current_entry->version    = value;
        else if (key == "url")      current_entry->url        = value;
        else if (key == "checksum") current_entry->checksum   = value;
        else if (key == "store")    current_entry->store_path = value;
        else if (key == "built") {
            if      (value == "source")        current_entry->build_kind = BuildKind::Source;
            else if (value == "prebuilt")      current_entry->build_kind = BuildKind::Prebuilt;
            else if (value == "astral-source") current_entry->build_kind = BuildKind::AstralSource;
            // Backwards compat: old lockfiles used "system"
            else if (value == "system")        current_entry->build_kind = BuildKind::AstralSource;
        }
        else if (key == "locked") lock.generated_at = value;
    }

    return lock;
}

void write(const Lockfile& lock, const std::filesystem::path& lock_path) {
    std::ostringstream oss;

    oss << "# Generated by astral-env lock — do not edit manually\n";
    oss << "# astral-env " << lock.astral_env_version << "\n";
    oss << "# locked: " << lock.generated_at << "\n\n";

    for (const auto& entry : lock.entries) {
        oss << "[" << entry.name << "]\n";
        oss << "version  = \"" << entry.version  << "\"\n";
        oss << "url      = \"" << entry.url      << "\"\n";
        oss << "checksum = \"" << entry.checksum << "\"\n";
        oss << "store    = \"" << entry.store_path.string() << "\"\n";
        oss << "built    = \"";
        switch (entry.build_kind) {
            case BuildKind::Source:       oss << "source";        break;
            case BuildKind::Prebuilt:     oss << "prebuilt";      break;
            case BuildKind::AstralSource: oss << "astral-source"; break;
        }
        oss << "\"\n\n";
    }

    util::write_file(lock_path, oss.str());
}

Lockfile generate(
    const std::filesystem::path& stars_path,
    const std::filesystem::path& repo_bin_dir,
    bool,
    const std::vector<std::string>&
) {
    Lockfile lock;
    lock.astral_env_version = config::version();
    lock.generated_at       = current_timestamp();

    if (!std::filesystem::exists(stars_path)) {
        throw std::runtime_error("File not found: " + stars_path.string());
    }

    std::string content = util::read_file(stars_path);
    std::istringstream iss(content);

    bool in_packages = false;
    std::string line;

    while (std::getline(iss, line)) {
        line = util::trim(line);
        if (line.empty() || line[0] == '#') continue;

        if (line.find("$ENV.Packages") != std::string::npos) { in_packages = true;  continue; }
        if (line == "};")                                      { in_packages = false; continue; }
        if (!in_packages)                                       continue;
        if (line.find("$ENV.") != std::string::npos)           continue;

        auto constraint = lock::parse_constraint(line);
        if (constraint.package.empty()) continue;

        LockEntry entry;

        try {
            auto result = lock::resolve(repo_bin_dir, constraint);

            if (result.kind == ResolveKind::BinRepo) {
                // ── From AOHARU bin/ ──────────────────────────────────────────
                const auto& bin = *result.entry;
                entry.name     = bin.name;
                entry.version  = bin.version;
                entry.url      = bin.url;
                entry.checksum = bin.checksum;
                entry.build_script = bin.build_script;

                entry.build_kind = (bin.build_script && !bin.build_script->empty())
                    ? BuildKind::Source
                    : BuildKind::Prebuilt;

                entry.store_path = store::store_path(
                    "/astral-env/store",
                    entry.name,
                    entry.version,
                    entry.checksum
                );

                std::cout << "  " << constraint.package << " " << entry.version
                          << " → store (" << (entry.build_kind == BuildKind::Source ? "source" : "prebuilt") << ")\n";

            } else {
                // ── AstralSource: astral -S at build time ─────────────────────
                // url/checksum/store_path are empty — those live in the AOHARU
                // recipe and are resolved by astral itself at build time.
                entry.name       = constraint.package;
                entry.version    = constraint.version; // empty = unconstrained
                entry.url        = "";
                entry.checksum   = "";
                entry.store_path = "";
                entry.build_kind = BuildKind::AstralSource;

                std::cout << "  " << constraint.package
                          << (constraint.version.empty() ? "" : " " + constraint.op + " " + constraint.version)
                          << " → astral source build\n";
            }

        } catch (const std::exception& e) {
            // -bin hard error — propagate
            std::cerr << "error: " << e.what() << "\n";
            throw;
        }

        lock.entries.push_back(entry);
    }

    return lock;
}

} // namespace lock
