#include "env/activation.hpp"
#include "util/file.hpp"
#include <sstream>
#include <unistd.h>
#include <sys/types.h>

namespace env {

std::string generate_activation_script(const EnvConfig& config) {
    std::ostringstream ss;
    
    ss << "# Generated by astral-env — do not edit\n";
    ss << "# This script is sourced when entering the environment\n\n";
    
    // Set metadata
    ss << "export ENV_NAME=\"" << config.name << "\"\n";
    ss << "export ASTRAL_ENV_ACTIVE=\"1\"\n";
    ss << "export ASTRAL_ENV_ROOT=\"$(pwd)\"\n\n";
    
    // Build PATH
    if (!config.store_paths.empty()) {
        ss << "# Prepend store bin directories to PATH\n";
        for (const auto& path : config.store_paths) {
            auto bin_path = path / "bin";
            ss << "export PATH=\"" << bin_path.string() << ":$PATH\"\n";
        }
        ss << "\n";
    }
    
    // Build LD_LIBRARY_PATH
    if (!config.store_paths.empty()) {
        ss << "# Prepend store lib directories to LD_LIBRARY_PATH\n";
        for (const auto& path : config.store_paths) {
            auto lib_path = path / "lib";
            ss << "export LD_LIBRARY_PATH=\"" << lib_path.string() << ":$LD_LIBRARY_PATH\"\n";
        }
        ss << "\n";
    }
    
    // Build PKG_CONFIG_PATH
    if (!config.store_paths.empty()) {
        ss << "# Prepend store pkgconfig directories to PKG_CONFIG_PATH\n";
        for (const auto& path : config.store_paths) {
            auto pkg_path = path / "lib" / "pkgconfig";
            ss << "export PKG_CONFIG_PATH=\"" << pkg_path.string() << ":$PKG_CONFIG_PATH\"\n";
        }
        ss << "\n";
    }
    
    // Build C_INCLUDE_PATH
    if (!config.store_paths.empty()) {
        ss << "# Prepend store include directories to C_INCLUDE_PATH\n";
        for (const auto& path : config.store_paths) {
            auto inc_path = path / "include";
            ss << "export C_INCLUDE_PATH=\"" << inc_path.string() << ":$C_INCLUDE_PATH\"\n";
        }
        ss << "\n";
    }
    
    // Export custom variables
    if (!config.vars.empty()) {
        ss << "# Custom environment variables\n";
        for (const auto& [key, value] : config.vars) {
            ss << "export " << key << "=\"" << value << "\"\n";
        }
        ss << "\n";
    }
    
    // Shell hook
    if (!config.shell_hook.empty()) {
        ss << "# Shell hook\n";
        ss << config.shell_hook << "\n";
    }
    
    return ss.str();
}

std::filesystem::path get_activation_script_path() {
    std::ostringstream ss;
    ss << "/tmp/astral-env-activate-" << getpid();
    return ss.str();
}

} // namespace env
